apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-py
  labels:
    app: deployment
    type: backend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend
    spec:
      containers:
      - name: python
        image: python
  replicas: 10
  selector:
    matchLabels:      
      type: backend




