apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-app
  labels:
    app: rs
    type: backend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend
    spec:
      containers:
      - name: redis-container
        image: redis
  replicas: 3
  selector:
    matchLabels:      
      type: backend




